repos:
    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: "" # Use the sha / tag you want to point at
      hooks:
          # - id: mypy
          #   name: mypy utils
          #   files: "^utils"
          #   additional_dependencies:
          #     - "pydantic"
          #     - "sqlalchemy-stubs"
          # - id: mypy
          #   name: mypy cdk stacks
          #   entry: mypy
          #   files: "^stacks\/.*"
            # additional_dependencies:
            #   - "boto3-stubs[all]"
            #   - "pydantic"
            #   - "sqlalchemy-stubs"
          - id: mypy
            name: mypy login
            files: "^microservices\/login"
            exclude: ".*\/tests"
            additional_dependencies:
              - "pydantic"
              - "sqlalchemy-stubs"
          - id: mypy
            name: mypy organization
            files: "^microservices\/organization"
            exclude: ".*\/tests"
            additional_dependencies:
              - "pydantic"
              - "sqlalchemy-stubs"
          - id: mypy
            name: mypy user
            files: "^microservices\/user"
            exclude: ".*\/tests"
            additional_dependencies:
              - "pydantic"
              - "sqlalchemy-stubs"
          - id: mypy
            name: mypy authorizer
            files: "^microservices\/authorizer"
            exclude: ".*\/tests"
            additional_dependencies:
              - "pydantic"
              - "sqlalchemy-stubs"
              - "boto3-stubs[sqs,dynamodb]"
    - repo: https://gitlab.com/pycqa/flake8
      rev: "" # pick a git hash / tag to point to
      hooks:
          - id: flake8
    - repo: https://github.com/psf/black
      rev: 19.10b0 # Replace by any tag/version: https://github.com/psf/black/tags
      hooks:
        - id: black
          language_version: python3 # Should be a command that runs python3.6+
