AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    Timeout: 300

Resources:
  CreateUserGroupsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: create_user_groups/
      Handler: app.lambda_handler
      Runtime: python3.8
      Environment:
        Variables:
          DB_PORT: ""
          DB_HOST: ""
          DB_NAME: ""
          DB_ENGINE: ""
          DB_USER: ""
          DB_PASSWORD: ""
      Events:
        CreateUserGroups:
          Type: Api
          Properties:
            Path: /userGroups
            Method: POST          
  DeleteUserGroupFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: delete_user_groups/
      Handler: app.lambda_handler
      Runtime: python3.8
      Environment:
        Variables:
          DB_PORT: ""
          DB_HOST: ""
          DB_NAME: ""
          DB_ENGINE: ""
          DB_USER: ""
          DB_PASSWORD: ""          
      Events:
        DeleteUserGroup:
          Type: Api
          Properties:
            Path: /userGroups/{id}
            Method: DELETE

  GetUserGroupsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: get_user_groups/
      Handler: app.lambda_handler
      Runtime: python3.8
      Environment:
        Variables:
          DB_PORT: ""
          DB_HOST: ""
          DB_NAME: ""
          DB_ENGINE: ""
          DB_USER: ""
          DB_PASSWORD: ""          
      Events:
        GetUserGroup:
          Type: Api
          Properties:
            Path: /userGroups/{id}
            Method: GET
        GetUserGroups:
          Type: Api
          Properties:
            Path: /userGroups
            Method: GET

  EditUserGroupFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: edit_user_group/
      Handler: app.lambda_handler
      Runtime: python3.8
      Environment:
        Variables:
          DB_PORT: ""
          DB_HOST: ""
          DB_NAME: ""
          DB_ENGINE: ""
          DB_USER: ""
          DB_PASSWORD: ""          
      Events:
        GetUserGroup:
          Type: Api
          Properties:
            Path: /userGroups/{id}
            Method: PUT
            