FROM public.ecr.aws/lambda/python:3.8

COPY ./validate_authorization/requirements.txt ./

RUN pip install -r requirements.txt

COPY lib/* /opt/lib/
COPY validate_authorization/* ./
COPY models/* models/
COPY database.py ./

CMD ["app.lambda_handler"]    