AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    Timeout: 300

Resources:
  CreateDeviceGroupFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: create_device_group/
      Handler: app.lambda_handler
      Runtime: python3.8
      Environment:
        Variables:
          DB_PORT: ""
          DB_HOST: ""
          DB_NAME: ""
          DB_ENGINE: ""
          DB_USER: ""
          DB_PASSWORD: ""
      Events:
        CreateDeviceGroups:
          Type: Api
          Properties:
            Path: /devices/groups
            Method: POST          
  DeleteDeviceGroupFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: delete_device_group/
      Handler: app.lambda_handler
      Runtime: python3.8
      Environment:
        Variables:
          DB_PORT: ""
          DB_HOST: ""
          DB_NAME: ""
          DB_ENGINE: ""
          DB_USER: ""
          DB_PASSWORD: ""          
      Events:
        DeleteDeviceGroup:
          Type: Api
          Properties:
            Path: /devices/groups/{id}
            Method: DELETE

  GetDeviceGroupsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: get_device_groups/
      Handler: app.lambda_handler
      Runtime: python3.8
      Environment:
        Variables:
          DB_PORT: ""
          DB_HOST: ""
          DB_NAME: ""
          DB_ENGINE: ""
          DB_USER: ""
          DB_PASSWORD: ""          
      Events:
        GetDeviceGroup:
          Type: Api
          Properties:
            Path: /devices/groups/{id}
            Method: GET
        GetDeviceGroups:
          Type: Api
          Properties:
            Path: /devices/groups
            Method: GET

  EditDeviceGroupFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: edit_device_group/
      Handler: app.lambda_handler
      Runtime: python3.8
      Environment:
        Variables:
          DB_PORT: ""
          DB_HOST: ""
          DB_NAME: ""
          DB_ENGINE: ""
          DB_USER: ""
          DB_PASSWORD: ""          
      Events:
        GetDeviceGroup:
          Type: Api
          Properties:
            Path: /devices/groups/{id}
            Method: PUT
            