AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  login

  Sample SAM Template for login

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  GenerateSessionFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: generate_session/
      Handler: app.lambda_handler
      Runtime: python3.8
      Timeout: 30
      Environment:
        Variables:
          LOGIN_ID: ""
          JWT_SECRET: ""
          DYNAMODB_ENDPOINT_OVERRIDE:
          SESSION_TABLE_NAME: !Ref SessionsTable
      Policies:
        - DynamoDBWritePolicy:
            TableName: !Ref SessionsTable     
      Events:
        GenerateSession:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /session
            Method: get
  GenerateJWTFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: generate_jwt/
      Handler: app.lambda_handler
      Runtime: python3.8
      Timeout: 30
      Environment:
        Variables:
          JWT_SECRET: ""
          DYNAMODB_ENDPOINT_OVERRIDE:
          SESSION_TABLE_NAME: !Ref SessionsTable
      Policies:
        - DynamoDBWritePolicy:
            TableName: !Ref SessionsTable     
      Events:
        GenerateSession:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /session/{id}
            Method: get
            RequestParameters:
              - method.request.header.Authorization:
                  Required: true
  LoginServiceFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: login_service/
      Handler: app.lambda_handler
      Runtime: python3.8
      Timeout: 30
      Environment:
        Variables:
          LOGIN_ID: ""
          ONBOARDING_PATH: ""
          LOGIN_SERVICE_PASSWORD: ""
          WALLET_PATH: ""
          DB_PORT: ""
          DB_HOST: ""
          DB_NAME: ""
          DB_ENGINE: ""
          DB_USER: ""
          DB_PASSWORD: ""
          NONCE_TABLE_NAME: ""
          DYNAMODB_ENDPOINT_OVERRIDE:
      Policies:
        - DynamoDBWritePolicy:
            TableName: !Ref SessionsTable     
      Events:
        GenerateSession:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /login
            Method: post
            # RequestParameters:
            #   - method.request.header.Authorization:
            #       Required: true                  
  ValidateNonceFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: validate_nonce/
      Handler: app.lambda_handler
      Runtime: python3.8
      Timeout: 30
      Environment:
        Variables:
          LOGIN_ID: ""
          LOGIN_SERVICE_PASSWORD: ""
          WALLET_PATH: ""
          DB_PORT: ""
          DB_HOST: ""
          DB_NAME: ""
          DB_ENGINE: ""
          DB_USER: ""
          DB_PASSWORD: ""
          NONCE_TABLE_NAME: !Ref NoncesTable
          SESSION_TABLE_NAME: !Ref SessionsTable
          DYNAMODB_ENDPOINT_OVERRIDE:
      Policies:
        - DynamoDBWritePolicy:
            TableName: !Ref SessionsTable 
        - DynamoDBWritePolicy:
            TableName: !Ref NoncesTable     
      Events:
        GenerateSession:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /login/validate
            Method: post
            # RequestParameters:
            #   - method.request.header.Authorization:
            #       Required: true                  

  SessionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: sessions
      AttributeDefinitions:
        - AttributeName: session_id
          AttributeType: S
        - AttributeName: status
          AttributeType: S
      KeySchema:
        - AttributeName: session_id
          KeyType: HASH
        - AttributeName: status
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST

  NoncesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: nonces
      AttributeDefinitions:
        - AttributeName: service_id
          AttributeType: S
        - AttributeName: message
          AttributeType: S
      KeySchema:
        - AttributeName: service_id
          KeyType: HASH
        - AttributeName: message
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  GenerateSessionApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  GenerateSessionFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt GenerateSessionFunction.Arn
  GenerateSessionFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt GenerateSessionFunctionRole.Arn
