AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  organization

  Sample SAM Template for organization

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  # CreateOrganizationFunction:
  #   Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
  #   Properties:
  #     CodeUri: create_organization/
  #     Handler: app.lambda_handler
  #     Runtime: python3.8
  #     Environment:
  #       Variables:
  #         DB_PORT: ""
  #         DB_HOST: ""
  #         DB_NAME: ""
  #         DB_ENGINE: ""
  #         DB_USER: ""
  #         DB_PASSWORD: ""
  # EditOrganizationFunction:
  #   Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
  #   Properties:
  #     CodeUri: edit_organization/
  #     Handler: app.lambda_handler
  #     Runtime: python3.8
  #     Environment:
  #       Variables:
  #         DB_PORT: ""
  #         DB_HOST: ""
  #         DB_NAME: ""
  #         DB_ENGINE: ""
  #         DB_USER: ""
  #         DB_PASSWORD: ""        
  # DeleteOrganizationFunction:
  #   Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
  #   Properties:
  #     CodeUri: delete_organization/
  #     Handler: app.lambda_handler
  #     Runtime: python3.8
  #     Environment:
  #       Variables:
  #         DB_PORT: ""
  #         DB_HOST: ""
  #         DB_NAME: ""
  #         DB_ENGINE: ""
  #         DB_USER: ""
  #         DB_PASSWORD: ""        
  GetOrganizationsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: get_organizations/
      Handler: app.lambda_handler
      Runtime: python3.8
      Environment:
        Variables:
          DB_PORT: ""
          DB_HOST: ""
          DB_NAME: ""
          DB_ENGINE: ""
          DB_USER: ""
          DB_PASSWORD: ""                    
      
      Events:
        # CreateOrganization:
        #   Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
        #   Properties:
        #     Path: /organizations
        #     Method: POST
        # EditOrganization:
        #   Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
        #   Properties:
        #     Path: /organizations/{id}
        #     Method: PUT
        # DeleteOrganization:
        #   Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
        #   Properties:
        #     Path: /organizations/{id}
        #     Method: DELETE
        # GetOrganization:
        #   Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
        #   Properties:
        #     Path: /organizations/{id}
        #     Method: GET   
        GetOrganizations:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /organizations
            Method: GET
            RequestParameters:     
              - method.request.querystring

